# Generated by Django 3.0.5 on 2020-04-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0003_auto_20200414_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='username',
            field=models.CharField(default='kp44512', max_length=50),
        ),
    ]
